server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # LOGIN ROUTES (NO JWT FILTER)
        - id: auth-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        # USER PROTECTED ROUTES
        - id: users-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true