server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: users-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthenticationFilter

        - id: products-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - JwtAuthenticationFilter

        - id: orders-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - JwtAuthenticationFilter

        - id: payments-route
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
            - JwtAuthenticationFilter

        - id: inventory-route
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
          filters:
            - JwtAuthenticationFilter

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: true
