server:
  port: 8083

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://mysql:3306/skinplus_inventory_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"